### ISSUE TITLE
toastr is not working anymore

### ISSUE THREAD

**Issue by integry** [english3/Riverside-frontend#12]
After separating the frontend code in the new repository, toastr messages do not show up anymore.

It can be tested from here for instance: http://localhost:4200/#/builder/1

After clicking the Save button here:

![image](https://user-images.githubusercontent.com/829273/73917526-48c8ce00-48c8-11ea-9bd1-f36c9effa4d8.png)

and the spinner disappears, it should show a toastr message like this:

![image](https://user-images.githubusercontent.com/829273/73917397-01424200-48c8-11ea-8bfd-1a1f19685dd9.png)

In this particular example toastr is called in src/app/module-builder/module-editor/module-editor.component.ts (line 108).

Please start a new branch from master and prefix the branch name with the ticket ID (for example, 12_toastr_fix)

**Comment by umbrellait-alexey-ovsyanikov** [comment]
Bug was fixed!
