### ISSUE TITLE
Checkbox selector template

### ISSUE THREAD

**Issue by integry** [english3/Riverside-frontend#17]
Specs - https://docs.google.com/document/d/1pt4YLd4my3yjtv9Yb-8VJbcLX35z8rhUxvSt3ZliWTs/edit#

**Comment by umbrella-kristina-gushchina** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Checkbox selector template #17](https://trello.com/c/ghucXhTR/9-checkbox-selector-template-17)
