### ISSUE TITLE
module-result template improvements

### ISSUE THREAD

**Issue by integry** [english3/Riverside-frontend#27]
1. By default the module-result template shows the output of the last step of the selected module. However sometimes we need to show output from an intermediate step. Add a configuration option for entering step ID (optional) - when a step ID (database ID, not sequential index) is entered, output of that step is displayed, otherwise by default it's still the last step.

2. Add ability to add 1 or more configuration key/value pairs. This will be used to customize the outputs by passing extra parameters to them. For example, we might pass parameters like `["color", "green"]`, `["nav", "carousel"]`, `["class", "compact"]`. Both key and value are arbitrary string inputs, although the keys will be expected to match the keys defined in target template data interface (for now we will not validate that).

Starting point of this task would be to edit the src/app/module-viewer/riverside-step-template/templates/module-result/index.ts file and modify the interface definition to make changes in form builder.

Next step would be heading to module builder - http://localhost:4200/#/builder/9 - you can use step 3 of Campaign Strategy module to test it. It should be looking like this:

![image](https://user-images.githubusercontent.com/829273/74194189-7d8aab80-4c61-11ea-98d4-c8308c848bd9.png)

The new fields would come at the bottom of the table. You can use 63 as the step ID value (step 11 of the ICP module - Assign Weight to Criteria) - this is the first target.

With the current configuration we see the last step of the ICP being embed:

![image](https://user-images.githubusercontent.com/829273/74195141-4a491c00-4c63-11ea-9c68-455cfd534275.png)

However we want the step 63, which looks like this:

![image](https://user-images.githubusercontent.com/829273/74195249-7bc1e780-4c63-11ea-8037-753a4f04c1b4.png)

Before rendering the target template, assign the configuration keys/values to `template_params_json`  (modify content before instantiating `TemplateContentData`).

Start a new branch from **master** (as this feature will be used in different modules).

**Comment by umbrella-kristina-gushchina** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [module-result template improvements](https://trello.com/c/gCg351Am/2-module-result-template-improvements)
