### ISSUE TITLE
Implement buyer personas overview as a carousel

### ISSUE THREAD

**Issue by integry** [english3/Riverside-frontend#28]
Don't work on this before #27 is completed
----
This is related to your previous task #27. The goal of this change is to implement the option to display the Buyer Personas module result as a carousel displaying one person per slide.

Here's the wireframe mock of step 4 of Content Strategy, which looks exactly the same as step 2 of Campaign Strategy:

![image](https://user-images.githubusercontent.com/829273/74199653-6b166f00-4c6d-11ea-95da-196cc019c3d7.png)

It uses the module-result template to display the output of Buyer Personas. However Buyer Personas output lists all the personas one after another (even though there is a navigation bar to quickly scroll to a particular persona):

![image](https://user-images.githubusercontent.com/829273/74199972-525a8900-4c6e-11ea-9586-0a9d26cfd093.png)

The template to modify is `final-feedback`. To implement the change, add a configuration option called "nav", which can have 2 options: "tabs" (default if left empty) or "slides". So, when using the module-result template, you can add the `["nav", "slides"]` key/value pair to configuration.

Embed persona pictures in the slide navigation circles and make them a bit larger than in the wireframe.

**Comment by lizarraga77** [comment]
Great idea about embedding persona pictures in the navigation circles @integry.

**Comment by umbrella-kristina-gushchina** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement buyer personas overview as a carousel](https://trello.com/c/a0k4wp8R/3-implement-buyer-personas-overview-as-a-carousel)
