### ISSUE TITLE
Radio button template

### ISSUE THREAD

**Issue by integry** [english3/Riverside-frontend#30]
This is very similar to the checkbox template that you already developed. In this case instead of checkboxes, we need to have radio buttons.

Wireframe example:
![image](https://user-images.githubusercontent.com/829273/74322804-2e419980-4d8d-11ea-8438-1514d33c58ff.png)

**Item data**

Items will have the following fields:
* title (required)
* description (optional)
* image (optional)

**Configuration**

Add the following configuration options:

* _Require selection_ (checkbox) - will control selection validation

* _View style_ (select) - with the following options - 
1. Title only
2. Title and description
3. Title, description and image

Changing the view style will affect the layout in Module Viewer. 1 will look like the wireframe above, 2 and 3 will be more condensed with smaller gaps between items.

----
Log this task under Serviceable Addressable Market

**Comment by umbrella-kristina-gushchina** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Radio button template #30](https://trello.com/c/akRrucTC/5-radio-button-template-30)
